config/routes.rb
LocalZoo::Application.routes.draw do
  resources :registrations

  get "home/index"
  devise_for :admins
  resources :carts
  
  get "places/refresh", as: :places_refresh
  
  resources :places

  devise_for :users
  resources :users
  
  post "carts/subtract", as: :carts_subtract
  
  
  
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  

  
  devise_scope :admins do
  authenticated :admin do
    root 'places#index', as: :authenticated_admin_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_admin_root
    end
  end
  
  
  get "home/api", as: :api
  post "carts/checkin", as: :checkin
  post "registrations/register", as: :register

   root to: "home#index", :as => 'home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
# Just what do these various declarations do? Basically, they add navigation
# capabilities to the model objects. Because we added the belongs_to declaration
# to LineItem, we can now retrieve its Product and display the book’s title:
# li = LineItem.find(...)
# puts "This line item is for #{li.product.title}"
#default_scope {order('updated_at DESC')}
#default_scope { where(color: 'red') }
belongs_to :place
belongs_to :user

  #class TeacherSchedule < ActiveRecord::Base
  #validates_uniqueness_of :teacher_id, scope: [:semester_id, :class_id]
  #class Person < ActiveRecord::Base
  #validates_uniqueness_of :user_name, scope: :account_id
  
  # validates_uniqueness_of :user_id, scope: :place_id, conditions: -> { where(checked_num: '1') }

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
	#logger.error("tudi tukaj")
	#@places = Place.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end
  
  
  def checkin
  
    #logger.error("u checkinu sam, placeid iz dolaznog jsona je: #{ params[:placeId]}")
	#logger.error("u checkinu sam, placeid iz dolaznog jsona je: #{ params[:userId]}")
	#id: params[:id]
	check_in = Cart.find_or_initialize_by(user_id: params[:userId], place_id: params[:placeId])	
	check_in.increment(:checked_num, by = 1)	
	
	if check_in.new_record?		  
	  check_in.save!	  
	else	
	 check_in.update!(checked_num: check_in.checked_num)
	end
	 
	#render text: 'Thanks for sending a GET request with cURL!'
	render json: {status: 'Success'}

	#respond_to do |format|	
    ##format.json { render action: 'show', status: :created, location: @cart }
	#format.json { status: :created, location: @cart }
    #end		
	
  end
  
  # POST /carts
  # POST /carts.json
  def create    
  
    # @cart = Cart.new(cart_params)
	# Me, creating a card with a user&place, not yet saving
	@user = current_user
	place = Place.find(params[:place_id])
	@cart = @user.carts.build(:place => place)
	@cart.increment(:checked_num, by = 1)

		
	# if new card save, 
	# else update cart.checked_num +1 for current user&place	
	
	#Finds the first record with the given attributes, or creates a record with the attributes if one is not found:
    ## Find the first user named "Penélope" or create a new one.
    #User.find_or_create_by(first_name: 'Penélope')
    ## => #<User id: 1, first_name: "Penélope", last_name: nil>
    # Cart.find_or_create_by(user_id: @user.id, place_id: place.id) => was working also
	check_in = Cart.find_or_initialize_by(user_id: @user.id, place_id: place.id)	
	check_in.increment(:checked_num, by = 1)	
	
	if check_in.new_record?		  
	  check_in.save!	  
	else	
	 check_in.update!(checked_num: check_in.checked_num)
	end
	 
	

	respond_to do |format|
	format.html { redirect_to home_path, notice: "#{@user.email} uspjesno ste se prijavili u #{place.name}" }
    format.json { render action: 'show', status: :created, location: @cart }
    end
	
	# Original create code:	
	#respond_to do |format|
    #  if @cart.save
    #    #format.html { redirect_to carts_path, notice: 'You have successfully checked in.' }
	#	format.html { redirect_to places_path, notice: "#{@user.email} uspjesno ste se prijavili u #{place.name}" }
    #    format.json { render action: 'show', status: :created, location: @cart }
    #  else
    #    format.html { render action: 'new' }
    #    format.json { render json: @cart.errors, status: :unprocessable_entity }
    #  end
    #end
  
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  
  def subtract
  @cart = Cart.find params[:id]
  
  logger.error("v sabtraktu sam")
  respond_to do |format|
	  
	  @cart.increment(:points, by = -1)
	  #@cart.update!(points: @cart.points)

	  # update_columns will omit updating the timestamp fields
	  @cart.update_columns(points: @cart.points)

	  
	  #logger.error("bodovi #{@cart.user.email}")
	  # def update
	  # Rails 3
      # @book = Book.find(params[:id]) 
      # if @book.update_attributes(params[:book])
	  # @house.update_attributes(:colour => newcolour)
	  # @book.update_attributes(params[:book][:title])
	  # @book.update_attributes(params[:book][:price])
	  
	  # Rails 4 @article.update_columns(article_params)
	  
	  #@cart.increment(:checked_num, by = 1)
	  
        format.html { redirect_to places_path, notice: "Bodovi smanjeni za korisnika #{@cart.user.email}" }
        format.json { head :no_content }
      
    end
  end
  
  def update
  # Here we have a cart id from the frontend
  @cart = Cart.find params[:id]
  logger.error("v updateu sam")
   
  #nekaj = @cart.give
  #if nekaj.to_s  == "add"
  #logger.error("tudi tukaj ne to_s #{nekaj} ")
  #end
  #logger.error("gotohell #{nekaj.to_s} ")

  respond_to do |format|
	  if @cart.update_attributes params[@cart.id]
	  @cart.increment(:points, by = 1)
	  
	  #@cart.update!(points: @cart.points)
	  # update_columns will omit updating the timestamp fields
	  @cart.update_columns(points: @cart.points)

	  # def update
	  # Rails 3
      # @book = Book.find(params[:id]) 
      # if @book.update_attributes(params[:book])
	  # @house.update_attributes(:colour => newcolour)
	  # @book.update_attributes(params[:book][:title])
	  # @book.update_attributes(params[:book][:price])
	  
	  # Rails 4 @article.update_columns(article_params)
	  
	  #@cart.increment(:checked_num, by = 1)
	  
        format.html { redirect_to places_path, notice: "Bodovi dodani za korisnika #{@cart.user.email}" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
  
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id, :place_id, :points, :checked_num)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.number_field :place_id %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :checked_num %><br>
    <%= f.number_field :checked_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h2>Prijave/korisnici</h2>

<table class="table table-bordered table-hover">
  <thead>
    <tr class="info">
      <th>Mjesto</th>
      <th>Korisnik</th>
      <th>Bodovi</th>
      <th>Ponuda</th>
	  <th>Prijave</th>
      <th>Zadnja prijava</th>
      <!--
	  <th></th>
	  <th></th>
	  <th></th>
	  -->
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
	    <td><%= cart.place.name %></td>
		<td><%= cart.user.email %></td>
        <td><%= cart.points %></td>
		<td><%= cart.place.rewards %></td>
		<td><%= cart.checked_num %></td>
		<td><%= cart.updated_at.strftime("%d.%m.%Y. %H:%M:%S") %></td>
        <!--
		<td><%#= link_to 'Show', cart %></td>
        <td><%#= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%#= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<p>
  <strong>Place:</strong>
  <%= @cart.place_id %>
</p>

<p>
  <strong>Points:</strong>
  <%= @cart.points %>
</p>

<p>
  <strong>Visits:</strong>
  <%= @cart.checked_num %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>