config/routes.rb
LocalZoo::Application.routes.draw do
  resources :registrations

  get "home/index"
  devise_for :admins
  resources :carts
  
  get "places/refresh", as: :places_refresh
  
  resources :places

  devise_for :users
  resources :users
  
  post "carts/subtract", as: :carts_subtract
  
  
  
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  

  
  devise_scope :admins do
  authenticated :admin do
    root 'places#index', as: :authenticated_admin_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_admin_root
    end
  end
  
  
  get "home/api", as: :api
  post "carts/checkin", as: :checkin
  post "registrations/register", as: :register

   root to: "home#index", :as => 'home'

end

app/models/place.rb
class Place < ActiveRecord::Base
has_many :users, :through => :carts
has_many :carts, dependent: :destroy


  #def add_visit(cart_id)
  #current_visit = carts.where(:place_id => place_id).first
  #  if current_visit
  #    current_visit.quantity += 1
  #  else
  #    current_visit = Cart.new(:place_id=>place_id)
  #    carts << current_visit
  #  end
  #current_visit
  #end
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    #@places = Place.all
	@places = Place.where(admin_id: current_admin.id)
	
	# Get carts which have places belonging to current_admin.id
	@carts = Cart.where(place_id: Place.where(admin_id: current_admin.id)).order("updated_at DESC")
	
	
  end


  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  def refresh
   @carts = Cart.where(place_id: Place.where(admin_id: current_admin.id)).order("updated_at DESC")
   #@carts = Cart.where(:conditions =>["updated_at >= ? AND updated_at <= ?", Time.now-20.seconds, Time.now])
   # User.where("id > ?", 200) 
   # Temp. hack!
   #@carts1 = Cart.where(place_id: Place.where(admin_id: current_admin.id) )
   #@carts  = @carts1.where("updated_at > ?",Time.now-3.seconds).order("updated_at DESC")
   
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :full_name, :description, :rewards, :image_url, :admin_id, :tel, :mob, :email, :address)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_checked_clients.html.erb
<% @carts.each do |cart| %>
	
	<tr>
	<td>
	<%= cart.user.email %></td>
	<td><strong><%= cart.place.name %></strong></td>
	<td><%= cart.updated_at.strftime("%d.%m.%Y. %H:%M:%S") %></td>
	<td><span class="badge alert-default"><%= cart.points %></span></td>
	<td>    
	<%= button_to(" + ", cart_path(id:cart.id, :place_id => cart.place.id, :user_id =>cart.user.id), :method => :patch,  :class=> "btn btn-default") %> </td>
    <td>
	<%= button_to(" - ", carts_subtract_path(id:cart.id, :place_id => cart.place.id, :user_id =>cart.user.id),  :class=> "btn btn-default") %></td>
	</tr>

	
	
<% end %>

app/views/places/_clients.html.erb
<h3>Vaši klijenti:</h3>
<table class ="table table-bordered table-hover" id="clients_table">
<tr class="alert-info">
	<th>Korisnik</th>
	<th>Mjesto </th>
	<th>Vrijeme prijave</th>
	<th>Bodovi </th>
	<th>Povećaj </th>
	<th>Smanji </th>
	</tr>
<% @carts.each do |cart| %>
	<tbody>
	<tr>
	<td>
	<%= cart.user.email %></td>
	<td><strong><%= cart.place.name %></strong></td>
	<td><%= cart.updated_at.strftime("%d.%m.%Y. %H:%M:%S") %></td>
	<td><span class="badge alert-default"><%= cart.points %></span></td>
	<td>    
	<%= button_to(" + ", cart_path(id:cart.id, :place_id => cart.place.id, :user_id =>cart.user.id), :method => :patch,  :class=> "btn btn-default") %> </td>
    <td>
	<%= button_to(" - ", carts_subtract_path(id:cart.id, :place_id => cart.place.id, :user_id =>cart.user.id),  :class=> "btn btn-default") %></td>
	</tr>
	</tbody>

	
	<%# Find all users checked to the places of the current_admin %>
	<%# get current_admin place and all users which have records in carts(for that place_id) %>
	<%#checked_users = User.find_by(user_id: current_user.id, place_id: place.id)%>
	
	
<% end %>
	</table>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Naziv %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Puni_naziv %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :Opis %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :Nagrada %><br>
    <%= f.text_field :rewards %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  
    <div class="field">
    <%= f.label :Tel %><br>
    <%= f.text_field :tel %>
  </div> 
    <div class="field">
    <%= f.label :Mob %><br>
    <%= f.text_field :mob %>
  </div>
    <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :Adresa %><br>
    <%= f.text_field :address %>
  </div>

	<%# Each new place has admin_id of the admin creating it %>
	<%= f.hidden_field :admin_id, :value => current_admin.id %>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<!--<h1><span class="label label-danger">@ Mjesta s LocalZoo-om</span></h1><br>-->
<script>
$(document).ready(function () {
    // will call refreshPartial every 3 seconds
    setInterval(refreshClientsPartial, 3000)

});

// calls action refreshing the partial
function refreshClientsPartial() {
  $.ajax({
    url: "places/refresh"
 })
}
</script>

<% @places.each do |place| %>

<div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
					<!--<span class="label label-default"></span>-->
                        <h3><strong><%= place.name %>&nbsp;</strong><td><%= place.description %></td></h3></h3>
                </div>
			<div class="panel-body">
			<table class ="table">
			<tr>
			<td>
			<%= image_tag(place.image_url, :class => 'img-rounded img-responsive') %></td>			
			<td><h4><strong><%= place.rewards %></h4>&nbsp; 
			
			<%# If there is no card, user has no points, so display zero - spaghetti code for sure%>
			<%# if cart = Cart.find_by(user_id: current_user.id, place_id: place.id).present?%>
			<%#cart = Cart.find_by(user_id: current_user.id, place_id: place.id)%>
			<%#=cart.points%>
			<%#else%>			
			<%# end %>
			</td>			
			<td><%#= button_to 'Check in', carts_path(:place_id => place), class: "btn btn-info pull-right" %></td>
			
			
			
			
			<td><%#= link_to 'Show', place %></td>
			<td><%= link_to 'Edit', edit_place_path(place),class: "btn btn-default pull-right" %></td>			
			<td><%#= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			
								
			<tr>			
			<td><footer class="text-muted"><%= place.full_name %> </footer> </td>			
			</tr>
			</table>
			</div>
			
	</div>
<% end %>
	<div id ="clients_table">
	  <%= render 'clients' %>
    </div>


<br>

<%= link_to 'Novi lokal', new_place_path, :class =>'btn btn-default' %>

app/views/places/new.html.erb
<h2>Podaci o lokalu</h2>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/refresh.js.erb
//alert ("refresh part je erb");
$('#clients_table').html('<%=escape_javascript(render 'clients', carts: @carts)%>');
//  This one works, appends rowa for just checked clients, not the whole table
//  To be used when model propagades change
	//$('#clients_table > tbody:first').append('<%=escape_javascript(render 'checked_clients', carts: @carts)%>');
//$(liData).appendTo('.products').fadeIn('slow');
//$("#clients_table tbody tr:nth-child(2)").fadeOut('slow').fadeIn(3000);
//$('#myTable > tbody:last').append('<tr>...</tr><tr>...</tr>');

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @place.full_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <strong>Rewards:</strong>
  <%= @place.rewards %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @place.image_url %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>