config/routes.rb
LocalZoo::Application.routes.draw do
  resources :registrations

  get "home/index"
  devise_for :admins
  resources :carts
  
  get "places/refresh", as: :places_refresh
  
  resources :places

  devise_for :users
  resources :users
  
  post "carts/subtract", as: :carts_subtract
  
  
  
  devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  

  
  devise_scope :admins do
  authenticated :admin do
    root 'places#index', as: :authenticated_admin_root
  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_admin_root
    end
  end
  
  
  get "home/api", as: :api
  post "carts/checkin", as: :checkin
  post "registrations/register", as: :register

   root to: "home#index", :as => 'home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Locarda - kartica vjernosti za sva vasa mala mjesta</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
body { padding-top: 70px; }
</style>
<body>

<!-- Navbar-->
<% if (user_signed_in? || admin_signed_in?) %>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".menu1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <% if admin_signed_in? %>
	<a class="navbar-brand" <%=link_to 'Locarda', places_path %>
	<% else %>
	<a class="navbar-brand" <%=link_to 'Locarda', home_path %>
	<% end %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse menu1" id="bs-example-navbar-collapse-1">    
	  <ul class="nav navbar-nav ">	   
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <!--<img src="/images/place2.jpg">--><b class="caret"></b></a>
        <ul class="dropdown-menu">
		  <li><%=link_to'Home', home_path%> </li>
		  <li class="divider"></li>		 
          <% if admin_signed_in?%>
		  <li><%=link_to 'Mjesta', places_path %></li>
		  <li class="divider"></li>
		  <li><%=link_to'Prijave', carts_path %> </li>
		  <li class="divider"></li>
		  <li><%=link_to' Log Out', destroy_admin_session_path, :method => :delete %> </li>
		  <% end %>
		  
		  <% if user_signed_in? %>
		   <li><%#=link_to'Admin', new_admin_session_path%> </li>		  		  		 
		  <li><%=link_to' Log Out', destroy_user_session_path, :method => :delete %> </li>
		  <% end %>
		  	  		  		 
		  
		   
		  
        </ul>
      </li>	  
    </ul>	
	 <% if user_signed_in? %>
		<p class="navbar-text pull-right">
		Signed in as <strong><%=current_user.email %></strong>. Not you? 
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>
	
	<% elsif admin_signed_in?%>
		<p class="navbar-text pull-right"><strong>Admin </strong><%=current_admin.email %>
		<%= link_to "Sign out", destroy_admin_session_path, :method => :delete %> </p></p>
	
	<% elsif !admin_signed_in? && !user_signed_in?%>
		<p class="navbar-text pull-right">
		<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %></p>
	<% end %>
 
  </div><!-- /.navbar-collapse -->
</nav>
<% end %>
	 

<div class="container">

<body>
<% if notice %>
 <div class="alert alert-info" role="alert"><p class="notice"><%= notice %></p></div>
<% end %>

<% if alert %>
 <div class="alert alert-danger"  role="alert"><p class="notice"><%= alert %></p></div>
<% end %>

<%= yield %>

</body>


    <% if user_signed_in? or admin_signed_in?%>
	<div class="text-center"
	<footer>
		<p class="text-muted">&copy; locarda.herokuapp.com</p>
	</footer>
	</div>
	<% end %>
</html>